packages:
  - packages/*
blockExoticSubdeps: false
catalog:
  "@biomejs/biome": ^2.5.0
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.2
  classnames: ^2.5.1
  framer-motion: ^12.40.0
  jotai-babel: ^0.2.0
  react: ^19.2.7
  react-dom: ^19.2.7
  vite: ^8.0.16
  vite-plugin-babel: ^1.6.0
  vite-plugin-svgr: ^5.2.0
  vite-plugin-wasm: ^3.6.0
allowBuilds:
  "@biomejs/biome": true
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
overrides:
  "@applemusic-like-lyrics/ttml": "git+https://github.com/ITManCHINA/applemusic-like-lyrics.git#8c0f9a96a255dbff042c26b23e5f68926daf1895&path:packages/ttml"
  "@applemusic-like-lyrics/lyric": "git+https://github.com/ITManCHINA/applemusic-like-lyrics.git#8c0f9a96a255dbff042c26b23e5f68926daf1895&path:packages/lyric"
  "@applemusic-like-lyrics/core": "git+https://github.com/ITManCHINA/applemusic-like-lyrics.git#8c0f9a96a255dbff042c26b23e5f68926daf1895&path:packages/core"
  "@applemusic-like-lyrics/react-full": "git+https://github.com/ITManCHINA/applemusic-like-lyrics.git#8c0f9a96a255dbff042c26b23e5f68926daf1895&path:packages/react-full"
  "@applemusic-like-lyrics/react": "git+https://github.com/ITManCHINA/applemusic-like-lyrics.git#8c0f9a96a255dbff042c26b23e5f68926daf1895&path:packages/react"
  "@ungap/structured-clone": "^1.3.0"
  "classnames": "^2.5.1"
  "framer-motion": "^12.38.0"
